Repository UnimibSoftEngCourse2022/homebrew-ferioli-pinciroli-trolli-spinelli-boolean-rhapsody, pull requests merged in 2024-02, with the labels that each got.

#9 Database servicelocator
  app/build.gradle.kts
  app/src/androidTest/java/it/unimib/brewday/ExampleInstrumentedTest.java
  app/src/androidTest/java/it/unimib/brewday/database/LocalDatabaseTest.java
  app/src/androidTest/java/it/unimib/brewday/util/ServiceLocatorTest.java
  app/src/main/java/it/unimib/brewday/database/LocalDatabase.java
  app/src/main/java/it/unimib/brewday/model/Attrezzo.java
  app/src/main/java/it/unimib/brewday/model/Ingrediente.java
  app/src/main/java/it/unimib/brewday/model/Ricetta.java
  app/src/main/java/it/unimib/brewday/util/Constants.java
  app/src/main/java/it/unimib/brewday/util/ServiceLocator.java
  app/src/test/java/it/unimib/brewday/ExampleUnitTest.java
  app/src/test/java/it/unimib/brewday/util/ServiceLocatorTest.java
Labels: testing

#11 Main activity with bottom navigation
  app/build.gradle.kts
  app/src/androidTest/java/it/unimib/brewday/BottomNavigationTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/it/unimib/brewday/MainActivity.java
  app/src/main/java/it/unimib/brewday/ui/AttrezziFragment.java
  app/src/main/java/it/unimib/brewday/ui/BirreFragment.java
  app/src/main/java/it/unimib/brewday/ui/CreaRicettaFragment.java
  app/src/main/java/it/unimib/brewday/ui/IngredientiFragment.java
  app/src/main/java/it/unimib/brewday/ui/ListaRicetteFragment.java
  app/src/main/java/it/unimib/brewday/ui/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_attrezzi.xml
  app/src/main/res/layout/fragment_birre.xml
  app/src/main/res/layout/fragment_crea_ricetta.xml
  app/src/main/res/layout/fragment_ingredienti.xml
  app/src/main/res/layout/fragment_lista_ricette.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/menu/top_app_bar.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: feature, testing, UI

#12 Caso d'uso Gestisci ingredienti
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/it/unimib/brewday/database/IngredienteDao.java
  app/src/main/java/it/unimib/brewday/database/LocalDatabase.java
  app/src/main/java/it/unimib/brewday/model/Ingrediente.java
  app/src/main/java/it/unimib/brewday/model/Risultato.java
  app/src/main/java/it/unimib/brewday/model/TipoIngrediente.java
  app/src/main/java/it/unimib/brewday/repository/IngredienteRepository.java
  app/src/main/java/it/unimib/brewday/ui/Callback.java
  app/src/main/java/it/unimib/brewday/ui/ListaRicetteFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/AdapterListViewListaIngredientiDisponibili.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/IngredienteViewModel.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/IngredienteViewModelFactory.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/IngredientiFragment.java
  app/src/main/java/it/unimib/brewday/util/Constants.java
  app/src/main/java/it/unimib/brewday/util/Converters.java
  app/src/main/java/it/unimib/brewday/util/ListaIngredienti.java
  app/src/main/java/it/unimib/brewday/util/ServiceLocator.java
  app/src/main/res/drawable/baseline_add_24.xml
  app/src/main/res/drawable/baseline_horizontal_rule_24.xml
  app/src/main/res/layout/fragment_ingredienti.xml
  app/src/main/res/layout/lista_ingredienti_singoli.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI

#13 Use case gestisci attrezzi
  app/build.gradle.kts
  app/src/androidTest/java/it/unimib/brewday/BottomNavigationTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/it/unimib/brewday/database/AttrezzoDao.java
  app/src/main/java/it/unimib/brewday/database/LocalDatabase.java
  app/src/main/java/it/unimib/brewday/model/Attrezzo.java
  app/src/main/java/it/unimib/brewday/model/Risultato.java
  app/src/main/java/it/unimib/brewday/model/TipoAttrezzo.java
  app/src/main/java/it/unimib/brewday/repository/AttrezziRepository.java
  app/src/main/java/it/unimib/brewday/repository/IngredienteRepository.java
  app/src/main/java/it/unimib/brewday/ui/AttrezziFragment.java
  app/src/main/java/it/unimib/brewday/ui/MainActivity.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/GestisciAttrezziAdapter.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/GestisciAttrezziFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/GestisciAttrezziViewModel.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/GestisciAttrezziViewModelFactory.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/IngredientiFragment.java
  app/src/main/java/it/unimib/brewday/util/Converters.java
  app/src/main/java/it/unimib/brewday/util/Costanti.java
  app/src/main/java/it/unimib/brewday/util/ServiceLocator.java
  app/src/main/res/drawable/plus_large_svgrepo_com.xml
  app/src/main/res/drawable/trash_can_svgrepo_com.xml
  app/src/main/res/layout/fragment_attrezzi.xml
  app/src/main/res/layout/fragment_gestisci_attrezzi.xml
  app/src/main/res/layout/one_card_row.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/tipi_di_attrezzo.xml
Labels: feature

#20 Fix ingredienti fragment
  app/build.gradle.kts
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/it/unimib/brewday/model/Ingrediente.java
  app/src/main/java/it/unimib/brewday/ui/IngredientiFragment.java
  app/src/main/java/it/unimib/brewday/ui/MainActivity.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/GestisciAttrezziFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/AdapterListViewListaIngredientiDisponibili.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/IngredientiFragment.java
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_ingredienti.xml
  app/src/main/res/layout/lista_ingredienti_singoli.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: bug

#25 Gestione ricette completato
  app/build.gradle.kts
  app/src/androidTest/java/it/unimib/brewday/util/GestioneRicetteTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/it/unimib/brewday/database/IngredienteDao.java
  app/src/main/java/it/unimib/brewday/database/LocalDatabase.java
  app/src/main/java/it/unimib/brewday/database/RicettaDao.java
  app/src/main/java/it/unimib/brewday/model/Attrezzo.java
  app/src/main/java/it/unimib/brewday/model/Ingrediente.java
  app/src/main/java/it/unimib/brewday/model/IngredienteRicetta.java
  app/src/main/java/it/unimib/brewday/model/Ricetta.java
  app/src/main/java/it/unimib/brewday/model/Risultato.java
  app/src/main/java/it/unimib/brewday/repository/RicetteRepository.java
  app/src/main/java/it/unimib/brewday/ui/CreaRicettaFragment.java
  app/src/main/java/it/unimib/brewday/ui/ListaRicetteFragment.java
  app/src/main/java/it/unimib/brewday/ui/MainActivity.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/AttrezziAdapter.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/AttrezziFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/AttrezziViewModel.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/AttrezziViewModelFactory.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/GestisciAttrezziFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/InserisciAttrezzoDialog.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/AdapterListViewListaIngredientiDisponibili.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/IngredienteViewModel.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/IngredienteViewModelFactory.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ingredienti/IngredientiFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/CreaRicettaFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/ListaRicetteFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/RicettaDettagliataFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/RicetteRecyclerViewAdapter.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/RicetteViewModel.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/RicetteViewModelFactory.java
  app/src/main/java/it/unimib/brewday/util/GestioneRicette.java
  app/src/main/java/it/unimib/brewday/util/ListaIngredienti.java
  app/src/main/java/it/unimib/brewday/util/RegistroErrori.java
  app/src/main/java/it/unimib/brewday/util/ServiceLocator.java
  app/src/main/res/drawable/baseline_delete_outline_24.xml
  app/src/main/res/layout/activity_mock.xml
  app/src/main/res/layout/elemento_lista_ricetta.xml
  app/src/main/res/layout/fragment_crea_ricetta.xml
  app/src/main/res/layout/fragment_gestisci_attrezzi.xml
  app/src/main/res/layout/fragment_ingredienti.xml
  app/src/main/res/layout/fragment_inserisci_attrezzo_dialog.xml
  app/src/main/res/layout/fragment_lista_ricette.xml
  app/src/main/res/layout/fragment_ricetta_dettagliata.xml
  app/src/main/res/layout/lista_ingredienti_singoli.xml
  app/src/main/res/layout/one_card_row.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
Labels: feature, testing, UI

#26 Fix Navigatione Bottom menu
  app/build.gradle.kts
  app/src/main/java/it/unimib/brewday/ui/CosaDevoPreparareOggiFragment.java
  app/src/main/res/layout/fragment_cosa_devo_preparare_oggi.xml
  app/src/main/res/layout/fragment_gestisci_attrezzi.xml
Labels: bug

#27 modificati test
  app/src/androidTest/java/it/unimib/brewday/BottomNavigationTest.java
  app/src/androidTest/java/it/unimib/brewday/util/GestioneRicetteTest.java
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/values/strings.xml
Labels: testing

#40 Conclusione della preparazione di una birra
  app/src/main/java/it/unimib/brewday/database/BirraDao.java
  app/src/main/java/it/unimib/brewday/model/Birra.java
  app/src/main/java/it/unimib/brewday/model/BirraConRicetta.java
  app/src/main/java/it/unimib/brewday/repository/BirraRepository.java
  app/src/main/java/it/unimib/brewday/ui/gestione_birra/BirraDettagliataFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestione_birra/BirraViewModel.java
  app/src/main/java/it/unimib/brewday/ui/gestione_birra/ListaBirreAdapter.java
  app/src/main/java/it/unimib/brewday/ui/gestione_birra/ListaBirreFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_attrezzi/AttrezziAdapter.java
  app/src/main/java/it/unimib/brewday/util/RegistroErrori.java
  app/src/main/res/drawable/calendar_today_24.xml
  app/src/main/res/layout/elemento_lista_attrezzo.xml
  app/src/main/res/layout/elemento_lista_birra.xml
Labels: feature, UI

#46 Cosa prepariamo oggi
  app/src/androidTest/java/it/unimib/brewday/util/RicetteUtilTest.java
  app/src/main/java/it/unimib/brewday/database/BirraDao.java
  app/src/main/java/it/unimib/brewday/database/RicettaDao.java
  app/src/main/java/it/unimib/brewday/domain/GestioneBirre.java
  app/src/main/java/it/unimib/brewday/domain/GestioneBirreUtil.java
  app/src/main/java/it/unimib/brewday/domain/IGestioneBirra.java
  app/src/main/java/it/unimib/brewday/domain/StrategiaOttimizzazione.java
  app/src/main/java/it/unimib/brewday/domain/StrategiaOttimizzazioneIngredienti.java
  app/src/main/java/it/unimib/brewday/domain/StrategiaOttimizzazioneLitri.java
  app/src/main/java/it/unimib/brewday/model/BirraConRicetta.java
  app/src/main/java/it/unimib/brewday/model/Risultato.java
  app/src/main/java/it/unimib/brewday/repository/AttrezziRepository.java
  app/src/main/java/it/unimib/brewday/repository/IngredientiRepository.java
  app/src/main/java/it/unimib/brewday/repository/RicetteRepository.java
  app/src/main/java/it/unimib/brewday/ui/CosaDevoPreparareOggiFragment.java
  app/src/main/java/it/unimib/brewday/ui/Topbar.java
  app/src/main/java/it/unimib/brewday/ui/cosa_prepariamo_oggi/CosaPrepariamoOggiFragment.java
  app/src/main/java/it/unimib/brewday/ui/cosa_prepariamo_oggi/CosaPrepariamoOggiViewModel.java
  app/src/main/java/it/unimib/brewday/ui/cosa_prepariamo_oggi/CosaPrepariamoOggiViewModelFactory.java
  app/src/main/java/it/unimib/brewday/ui/gestione_birra/BirraViewModel.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/CreaRicettaFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/RicettaDettagliataFragment.java
  app/src/main/java/it/unimib/brewday/ui/gestisci_ricette/RicetteUtil.java
  app/src/main/java/it/unimib/brewday/ui/visualizza_birre/AdapterRecyclerViewNoteDegustazione.java
  app/src/main/java/it/unimib/brewday/ui/visualizza_birre/VisualizzaBirreViewModel.java
  app/src/main/java/it/unimib/brewday/util/Ottimizzazione.java
  app/src/main/java/it/unimib/brewday/util/ServiceLocator.java
  app/src/main/res/layout/fragment_cosa_devo_preparare_oggi.xml
  app/src/main/res/layout/fragment_cosa_prepariamo_oggi.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/it/unimib/brewday/domain/GestioneBirreUtilTest.java
  app/src/test/java/it/unimib/brewday/domain/StrategiaOttimizzazioneIngredientiTest.java
  app/src/test/java/it/unimib/brewday/domain/StrategiaOttimizzazioneLitriTest.java
  app/src/test/java/it/unimib/brewday/util/OttimizzazioneTest.java
Labels: feature, testing
